name: 'Hackbot CI'
description: 'Hackbot action'

inputs:
  bot_address:
    description: 'The address of the bot to hack'
    required: false
    default: 'localhost'
  bot_port:
    description: 'The port of the bot to hack'
    required: false
    default: '5000'
  token:
    description: 'The token to use to authenticate with the bot'
    required: true

runs:
  using: "composite"
  steps:

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        cache: 'pip' 
        python-version: '3.12'
        run: |
          pip install aiohttp
          pip install requests

    - name: Hack the contract (local source)
      id: hack_results
      shell: bash
      run: |        
        PATH="${{ github.action_path }}:$PATH" ./src/execute.sh \
          ${{ inputs.bot_address }} ${{ inputs.bot_port }} ${{ inputs.token }}

    # - name: Test token
    #   shell: bash
    #   run: |
    #     echo "Token: ${{ inputs.token }}"
    #     python3 <<EOF
    #     import requests
        
    #     url = f"http://${{ inputs.bot_address }}:${{ inputs.bot_port }}/api/test_token"
    #     headers = {'Authorization': f"Bearer ${{ inputs.token }}"}
        
    #     response = requests.get(url, headers=headers)
    #     print(f"Status code: {response.status_code}")
    #     print(f"Response text: {response.text}")
    #     EOF

outputs:
  hack_results:
    description: "The results of the hack"
    value: ${{ steps.hack_results.outputs.results }}
