name: 'Repository Info Action'
description: 'Get information about the current repository'
inputs:
  repo:
    description: 'The current repository in the format owner/repo'
    required: true
    default: ${{ github.repository }}
  ref:
    description: 'The current branch or tag in the format branch/tag'
    required: true
    default: ${{ github.ref_name }}

runs:
  using: "composite"
  steps:
    - name: Print Repository Info
      shell: bash
      run: |
        echo "Repository: ${{ inputs.repo }}"
        echo "Ref: ${{ inputs.ref }}"

    - name: Get Additional Repo Info
      shell: bash
      run: |
        echo "Current Branch: ${{ github.ref_name }}"
        echo "Workflow Triggering Event: ${{ github.event_name }}"
        echo "Action Running On: ${{ runner.os }}"

outputs:
  repo_full_name:
    description: "The full name of the repository"
    value: ${{ inputs.repo }}