name: 'Repository Info Action'
description: 'Get information about the current repository'

runs:
  using: "python3"
  main: "dist/index.py"

outputs:
  repo_full_name:
    description: "The full name of the repository"
    value: ${{ github.repository }}