name: 'Repository Info Action'
description: 'Get information about the current repository'
inputs:
  repo:
    description: 'The current repository in the format owner/repo'
    required: true
    default: ${{ github.repository }}

runs:
  using: "composite"
  steps:
    - name: Print Repository Info
      shell: bash
      run: |
        echo "Repository: ${{ inputs.repo }}"
        IFS='/' read -r owner repo <<< "${{ inputs.repo }}"
        echo "Owner: $owner"
        echo "Repo Name: $repo"

    - name: Get Additional Repo Info
      shell: bash
      run: |
        echo "Current Branch: ${{ github.ref_name }}"
        echo "Workflow Triggering Event: ${{ github.event_name }}"
        echo "Action Running On: ${{ runner.os }}"

outputs:
  repo_full_name:
    description: "The full name of the repository"
    value: ${{ inputs.repo }}
  repo_owner:
    description: "The owner of the repository"
    value: ${{ steps.split_repo.outputs.owner }}
  repo_name:
    description: "The name of the repository"
    value: ${{ steps.split_repo.outputs.repo }}