name: 'Hackbot CI'
description: 'Hackbot action'

inputs:
  bot_address:
    description: 'The address of the bot to hack'
    required: false
    default: 'localhost'
  bot_port:
    description: 'The port of the bot to hack'
    required: false
    default: '5000'
  token:
    description: 'The token to use to authenticate with the bot'
    required: true
outputs:
  hack_results:
    description: "The results of the hack"
    value: ${{ steps.hack_contract.outputs.results }}

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        cache: 'pip' 
        python-version: '3.12'

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install aiohttp requests

    - name: Hack the contract
      id: hack_contract
      shell: bash
      run: |       
        ${{ github.action_path }}/src/compress.sh
        python ${{ github.action_path }}/src/bot_api.py \
          --bot_address ${{ inputs.bot_address }} \
          --bot_port ${{ inputs.bot_port }} \
          --token ${{ inputs.token }}
        mkdir logs
        mv results.json logs/results.json

    - name: Upload logs
      uses: actions/upload-artifact@v4
      with:
        name: hack-logs
        path: logs
      retention-days:90
