name: 'Repository Info Action'
description: 'Get information about the current repository'
inputs:
  repo:
    description: 'The current repository in the format owner/repo'
    required: true
    default: ${{ github.repository }}
  ref:
    description: 'The current branch or tag in the format branch/tag'
    required: true
    default: ${{ github.ref_name }}

runs:
  using: "composite"
  steps:
    - name: Print Repository Info
      shell: bash
      run: |
        echo "Repository: ${{ inputs.repo }}"
        echo "Ref: ${{ inputs.ref }}"
        echo "Location: ${{ github.workspace }}"
        echo "Actor: ${{ github.actor }}"
        echo "Run ID: ${{ github.run_id }}"
        echo "Run Number: ${{ github.run_number }}"
        echo "Job ID: ${{ github.job_id }}"
        echo "Job Name: ${{ github.job_name }}"
        echo "Runner: ${{ runner.name }}"
        echo "Runner OS: ${{ runner.os }}"
        echo "Runner Arch: ${{ runner.arch }}"
        echo "Runner Env: ${{ runner.env }}"
        echo "Runner Temp Dir: ${{ runner.temp }}"
        echo "Runner Tool Cache: ${{ runner.tool_cache }}"
        echo "Runner Workdir: ${{ runner.workdir }}"
        echo "Repository Size: ${{ github.repository_size }}"
        echo "Repository ID: ${{ github.repository_id }}"
        echo "Repository Owner: ${{ github.repository_owner }}"
        echo "Repository Name: ${{ github.repository_name }}"
        echo "Repository URL: ${{ github.repository_url }}"
        echo "Repository Clone URL: ${{ github.repository_clone_url }}"
        echo "Repository Default Branch: ${{ github.repository_default_branch }}"
        echo "Repository Private: ${{ github.repository_private }}"
        echo "Repository Fork: ${{ github.repository_fork }}"
        echo "Repository: ${{ github.repository }}"

    - name: Get Additional Repo Info
      shell: bash
      run: |
        echo "Current Branch: ${{ github.ref_name }}"
        echo "Workflow Triggering Event: ${{ github.event_name }}"
        echo "Action Running On: ${{ runner.os }}"

outputs:
  repo_full_name:
    description: "The full name of the repository"
    value: ${{ inputs.repo }}